Repository riseupgroup/ticketcontrol, pull requests merged in 2022-06, with the labels that each got.

#64 55 add dark mode
  app/templates/dashboard.html
  app/templates/navbar.html
  app/templates/ticket/detail.html
  app/templates/ticket/manage.html
  app/templates/ticket/my.html
  app/templates/user/group/create.html
  app/templates/user/group/edit.html
  app/templates/user/register.html
  app/ticketcontrol/migrations/0017_alter_ticket_options_alter_ticket_moderators_and_more.py
  app/ticketcontrol/models.py
  app/ticketcontrol/static/css/colors.css
  app/ticketcontrol/static/css/custom.css
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
Labels: bug, enhancement

#67 add options to change ticket assignment and delete participants
  app/templates/ticket/detail.html
  app/ticketcontrol/static/js/ticket.js
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
Labels: bug, enhancement

#69 translation-to-german
  app/templates/category/create.html
  app/templates/category/edit.html
  app/templates/category/manage.html
  app/templates/dashboard.html
  app/templates/email/activate_mail.html
  app/templates/email/passwordreset_mail.html
  app/templates/footer.html
  app/templates/imprint.html
  app/templates/main.html
  app/templates/navbar.html
  app/templates/privacy.html
  app/templates/settings.html
  app/templates/ticket/detail.html
  app/templates/ticket/manage.html
  app/templates/ticket/my.html
  app/templates/ticket/new.html
  app/templates/user/activate.html
  app/templates/user/create.html
  app/templates/user/detail.html
  app/templates/user/edit.html
  app/templates/user/group/create.html
  app/templates/user/group/edit.html
  app/templates/user/group/manage.html
  app/templates/user/login.html
  app/templates/user/manage.html
  app/templates/user/passwordreset.html
  app/templates/user/passwordreset_request.html
  app/templates/user/register.html
  app/ticketcontrol/views.py
Labels: enhancement

#70 fix-buttons-on-safari
  app/templates/dashboard.html
  app/templates/settings.html
  app/templates/ticket/detail.html
  app/templates/ticket/my.html
  app/templates/ticket/new.html
Labels: bug
