Repository riseupgroup/ticketcontrol, pull requests merged in 2022-07, with the labels that each got.

#71 Insert Default Text
  app/settings/settings.json.example
  app/templates/home.html
  app/templates/imprint.html
  app/templates/privacy.html
Labels: enhancement

#84 fix encoding and switch to mysql
  app/ticketcontrol/settings.py
  docker-compose-ci.yaml
  docker-compose-dev.yaml
  docker-compose-prod.yaml
  docker-compose-pwd.yml
Labels: bug

#90 88 use docker socket to restart container
  Dockerfile
  app/templates/settings.html
  app/ticketcontrol/static/js/settings.js
  app/ticketcontrol/views.py
  docker-compose-ci.yaml
  docker-compose-dev.yaml
  docker-compose-prod.yaml
  docker-compose-pwd.yml
Labels: enhancement

#89 77 filter for users
  app/templates/ticket/manage.html
  app/templates/user/manage.html
  app/ticketcontrol/static/css/colors.css
  app/ticketcontrol/static/js/filter.js
  app/ticketcontrol/views.py
Labels: enhancement

#91 Fix ticket detail view
  app/templates/category/create.html
  app/templates/category/edit.html
  app/templates/ticket/detail.html
  app/templates/ticket/new.html
  app/templates/user/create.html
  app/templates/user/edit.html
  app/templates/user/group/create.html
  app/templates/user/group/edit.html
  app/templates/user/register.html
  app/ticketcontrol/static/js/edit.js
  app/ticketcontrol/static/js/ticket.js
  app/ticketcontrol/views.py
Labels: bug, enhancement
