Repository riseupgroup/ticketcontrol, pull requests merged in 2022-04, with the labels that each got.

#10 Fix docker compose 3
  Dockerfile
  app/ticketcontrol/migrations/0004_comment_user.py
  docker-compose-ci.yaml
  docker-compose-dev.yaml
  docker-compose-prod.yaml
  docker-compose-pwd.yml
  scripts/run.sh
Labels: bug

#13 Improve-ui
  app/templates/main.html
  app/templates/navbar.html
  app/templates/ticket/detail.html
  app/ticketcontrol/migrations/0008_alter_ticket_status.py
  app/ticketcontrol/models.py
Labels: enhancement

#11 Enhance run configuration
  app/.run/dev-compose.run.xml
  app/.run/ticketcontrol.run.xml
Labels: enhancement

#14 Minor fixes
  README.md
  app/.run/dev-compose.run.xml
  app/.run/ticketcontrol.run.xml
  app/README.md
  app/templates/dashboard.html
  app/templates/error.html
  app/templates/main.html
  app/templates/navbar.html
  app/templates/registration/login.html
  app/templates/registration/register.html
  app/templates/ticket/manage.html
  app/templates/ticket/new.html
  app/templates/user/create.html
  app/templates/user/delete.html
  app/templates/user/details.html
  app/templates/user/edit.html
  app/templates/user/group/create.html
  app/templates/user/group/delete.html
  app/templates/user/group/edit.html
  app/templates/user/group/manage.html
  app/templates/user/login.html
  app/templates/user/manage.html
  app/templates/user/register.html
  app/ticketcontrol/admin.py
  app/ticketcontrol/migrations/0001_initial.py
  app/ticketcontrol/migrations/0002_alter_ticket_moderator_alter_ticket_participating.py
  app/ticketcontrol/migrations/0003_alter_ticket_moderator_alter_ticket_participating.py
  app/ticketcontrol/migrations/0004_remove_user_role.py
  app/ticketcontrol/migrations/0005_alter_user_options.py
  app/ticketcontrol/migrations/0006_permission.py
  app/ticketcontrol/migrations/0007_comment_user.py
  app/ticketcontrol/migrations/0008_alter_ticket_status.py
  app/ticketcontrol/models.py
  app/ticketcontrol/settings.py
  app/ticketcontrol/static/js/login/login.js
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
  docker-compose-ci.yaml
  docker-compose-dev.yaml
Labels: bug, enhancement

#15 Ticket design and functionality
  app/.run/dev-compose build.run.xml
  app/templates/dashboard.html
  app/templates/navbar.html
  app/templates/registration/login.html
  app/templates/registration/register.html
  app/templates/ticket/detail.html
  app/templates/ticket/manage.html
  app/templates/ticket/new.html
  app/templates/user/create.html
  app/templates/user/edit.html
  app/templates/user/group/create.html
  app/templates/user/group/edit.html
  app/templates/user/register.html
  app/ticketcontrol/fixtures/00001-permissions.json
  app/ticketcontrol/fixtures/00002-groups.json
  app/ticketcontrol/fixtures/00003-admin_user.json
  app/ticketcontrol/fixtures/00004-categories.json
  app/ticketcontrol/fixtures/00005-contenttypes.json
  app/ticketcontrol/models.py
  app/ticketcontrol/static/css/custom.css
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
  docker-compose-dev.yaml
  scripts/run.sh
Labels: enhancement

#16 Redesign login and register view
  app/templates/user/login.html
  app/templates/user/register.html
Labels: enhancement

#27 Add confirm and password reset email merge main
  app/templates/user/activate.html
  app/templates/user/activate_mail.html
  app/templates/user/delete.html
  app/templates/user/details.html
  app/templates/user/edit.html
  app/templates/user/login.html
  app/templates/user/passwordreset.html
  app/templates/user/passwordreset_mail.html
  app/templates/user/passwordreset_request.html
  app/ticketcontrol/initial_data.py
  app/ticketcontrol/migrations/0011_alter_user_options_user_email_confirmed_and_more.py
  app/ticketcontrol/migrations/0012_user_new_email.py
  app/ticketcontrol/models.py
  app/ticketcontrol/settings.py
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
  docker-compose-ci.yaml
  docker-compose-dev.yaml
  docker-compose-prod.yaml
  requirements.txt
Labels: enhancement, feature

#26 Fix ticket detail view
  app/templates/ticket/detail.html
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
Labels: enhancement

#28 fix ticket comments
  app/templates/dashboard.html
  app/templates/ticket/detail.html
  app/templates/ticket/manage.html
  app/ticketcontrol/views.py
Labels: bug
