Repository riseupgroup/ticketcontrol, pull requests merged in 2022-05, with the labels that each got.

#31 redesign of several pages
  .env.example
  app/templates/dashboard.html
  app/templates/email/activate_mail.html
  app/templates/email/passwordreset_mail.html
  app/templates/half_page.html
  app/templates/home.html
  app/templates/main.html
  app/templates/navbar.html
  app/templates/ticket/manage.html
  app/templates/user/activate.html
  app/templates/user/create.html
  app/templates/user/delete.html
  app/templates/user/details.html
  app/templates/user/edit.html
  app/templates/user/group/create.html
  app/templates/user/group/delete.html
  app/templates/user/group/edit.html
  app/templates/user/group/manage.html
  app/templates/user/login.html
  app/templates/user/manage.html
  app/templates/user/passwordreset.html
  app/templates/user/passwordreset_request.html
  app/templates/user/register.html
  app/ticketcontrol/models.py
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
Labels: enhancement

#42 Ticket options delete and hide
  app/templates/ticket/detail.html
  app/ticketcontrol/migrations/0013_ticket_hidden.py
  app/ticketcontrol/models.py
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
Labels: feature

#44 Add ticket info update and location field to ticket
  app/templates/ticket/detail.html
  app/templates/ticket/new.html
  app/ticketcontrol/migrations/0014_alter_ticket_options_ticket_location.py
  app/ticketcontrol/models.py
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
Labels: enhancement, feature

#45 add settings and categories management
  .gitignore
  app/settings/settings.json.example
  app/templates/category/create.html
  app/templates/category/edit.html
  app/templates/category/manage.html
  app/templates/navbar.html
  app/templates/settings.html
  app/ticketcontrol/settings.py
  app/ticketcontrol/static/js/emailWhitelist.js
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
  docker-compose-ci.yaml
  docker-compose-dev.yaml
  docker-compose-prod.yaml
  docker-compose-pwd.yml
Labels: enhancement, feature

#48 Fix deleting of user with ticket and comments
  app/templates/ticket/detail.html
  app/ticketcontrol/models.py
  app/ticketcontrol/views.py
Labels: bug

#47 make ticket and comment editable
  app/templates/ticket/detail.html
  app/ticketcontrol/static/js/edit.js
  app/ticketcontrol/urls.py
  app/ticketcontrol/views.py
Labels: enhancement

#50 add ghost user to initial data
  app/ticketcontrol/initial_data.py
  app/ticketcontrol/views.py
Labels: bug

#51 show ticket options
  app/templates/navbar.html
  app/templates/ticket/detail.html
  app/templates/user/manage.html
  app/ticketcontrol/initial_data.py
  app/ticketcontrol/migrations/0015_alter_ticket_options.py
  app/ticketcontrol/models.py
  app/ticketcontrol/views.py
Labels: enhancement

#56 22 create optional e-mail whitelist
  app/templates/settings.html
  app/templates/user/activate.html
  app/ticketcontrol/static/js/emailWhitelist.js
  app/ticketcontrol/views.py
Labels: enhancement

#57 46 redesign settings
  app/templates/category/create.html
  app/templates/category/edit.html
  app/templates/category/manage.html
  app/templates/navbar.html
  app/templates/settings.html
  app/ticketcontrol/static/js/emailWhitelist.js
Labels: enhancement
